// Generated from Yamaha PSR-SX900/SX700 Pre-installed Expansion Contents List.
import 'sound_source.dart';
import 'style.dart';
import 'voice.dart';

const sx700ExpansionVoices = <SxVoice>[
  SxVoice(name: 'AfricanBigKit', category: 'African', type: 'Live!SFX', msb: 126, lsb: 0, pc: 52, slot: 0, source: SoundSource.expansion),
  SxVoice(name: 'BabyTalkingDrum', category: 'African', type: 'Live!SFX', msb: 126, lsb: 0, pc: 53, slot: 1, source: SoundSource.expansion),
  SxVoice(name: 'MotherTalkingDrum', category: 'African', type: 'Live!SFX', msb: 126, lsb: 0, pc: 54, slot: 2, source: SoundSource.expansion),
  SxVoice(name: 'AccordionKabina1', category: 'Europe', type: 'Regular', msb: 49, lsb: 4, pc: 13, slot: 3, source: SoundSource.expansion),
  SxVoice(name: 'AccordionKabina2', category: 'Europe', type: 'Regular', msb: 49, lsb: 9, pc: 10, slot: 4, source: SoundSource.expansion),
  SxVoice(name: 'AccordionOrgan1', category: 'Europe', type: 'Regular', msb: 49, lsb: 9, pc: 11, slot: 5, source: SoundSource.expansion),
  SxVoice(name: 'BabyBass', category: 'Europe', type: 'Regular', msb: 49, lsb: 5, pc: 12, slot: 6, source: SoundSource.expansion),
  SxVoice(name: 'BajanCombi L+R', category: 'Europe', type: 'Regular', msb: 49, lsb: 4, pc: 14, slot: 7, source: SoundSource.expansion),
  SxVoice(name: 'BalalaikaPluck', category: 'Europe', type: 'Regular', msb: 49, lsb: 4, pc: 15, slot: 8, source: SoundSource.expansion),
  SxVoice(name: 'BalalaikaTrem', category: 'Europe', type: 'Regular', msb: 49, lsb: 4, pc: 16, slot: 9, source: SoundSource.expansion),
  SxVoice(name: 'BalkanClarinet', category: 'Europe', type: 'Regular', msb: 49, lsb: 9, pc: 18, slot: 10, source: SoundSource.expansion),
  SxVoice(name: 'BandurriaTrem', category: 'Europe', type: 'Regular', msb: 49, lsb: 5, pc: 42, slot: 11, source: SoundSource.expansion),
  SxVoice(name: 'BaritonStac', category: 'Europe', type: 'Regular', msb: 49, lsb: 4, pc: 7, slot: 12, source: SoundSource.expansion),
  SxVoice(name: 'BouzoukiPluck', category: 'Europe', type: 'Regular', msb: 49, lsb: 2, pc: 13, slot: 13, source: SoundSource.expansion),
  SxVoice(name: 'BraciMega', category: 'Europe', type: 'Live!', msb: 49, lsb: 9, pc: 3, slot: 14, source: SoundSource.expansion),
  SxVoice(name: 'BraciSpiccato', category: 'Europe', type: 'Live!', msb: 49, lsb: 9, pc: 30, slot: 15, source: SoundSource.expansion),
  SxVoice(name: 'ContrabasBun', category: 'Europe', type: 'Regular', msb: 49, lsb: 9, pc: 6, slot: 16, source: SoundSource.expansion),
  SxVoice(name: 'ContrabasShort', category: 'Europe', type: 'Regular', msb: 49, lsb: 9, pc: 29, slot: 17, source: SoundSource.expansion),
  SxVoice(name: 'CymbalonMega', category: 'Europe', type: 'Live!', msb: 49, lsb: 9, pc: 1, slot: 18, source: SoundSource.expansion),
  SxVoice(name: 'CymbalonOpenAll', category: 'Europe', type: 'Live!', msb: 49, lsb: 9, pc: 25, slot: 19, source: SoundSource.expansion),
  SxVoice(name: 'Drumbla&Whistles', category: 'Europe', type: 'Regular', msb: 49, lsb: 9, pc: 42, slot: 20, source: SoundSource.expansion),
  SxVoice(name: 'FatSawHook', category: 'Europe', type: 'Regular', msb: 49, lsb: 9, pc: 43, slot: 21, source: SoundSource.expansion),
  SxVoice(name: 'FatSawPad', category: 'Europe', type: 'Regular', msb: 49, lsb: 9, pc: 46, slot: 22, source: SoundSource.expansion),
  SxVoice(name: 'FiddleShort', category: 'Europe', type: 'Regular', msb: 49, lsb: 4, pc: 20, slot: 23, source: SoundSource.expansion),
  SxVoice(name: 'FlamGuitarRhy', category: 'Europe', type: 'Regular', msb: 49, lsb: 5, pc: 9, slot: 24, source: SoundSource.expansion),
  SxVoice(name: 'FlamGuitarSolo', category: 'Europe', type: 'Regular', msb: 49, lsb: 5, pc: 8, slot: 25, source: SoundSource.expansion),
  SxVoice(name: 'FujaraEndingVel', category: 'Europe', type: 'Regular', msb: 49, lsb: 9, pc: 38, slot: 26, source: SoundSource.expansion),
  SxVoice(name: 'GajdaCombiG', category: 'Europe', type: 'Regular', msb: 49, lsb: 4, pc: 12, slot: 27, source: SoundSource.expansion),
  SxVoice(name: 'ItalianBandon', category: 'Europe', type: 'Regular', msb: 49, lsb: 5, pc: 1, slot: 28, source: SoundSource.expansion),
  SxVoice(name: 'ItalianMaster', category: 'Europe', type: 'Regular', msb: 49, lsb: 5, pc: 2, slot: 29, source: SoundSource.expansion),
  SxVoice(name: 'ItalianTenorsax', category: 'Europe', type: 'Regular', msb: 49, lsb: 5, pc: 4, slot: 30, source: SoundSource.expansion),
  SxVoice(name: 'Jew\'sHrp+Whistle', category: 'Europe', type: 'Regular', msb: 49, lsb: 4, pc: 22, slot: 31, source: SoundSource.expansion),
  SxVoice(name: 'JPShortSeq', category: 'Europe', type: 'Regular', msb: 49, lsb: 9, pc: 47, slot: 32, source: SoundSource.expansion),
  SxVoice(name: 'LaudFing&Trem', category: 'Europe', type: 'Regular', msb: 49, lsb: 5, pc: 43, slot: 33, source: SoundSource.expansion),
  SxVoice(name: 'LaudTrem', category: 'Europe', type: 'Regular', msb: 49, lsb: 5, pc: 45, slot: 34, source: SoundSource.expansion),
  SxVoice(name: 'NuTrumpet', category: 'Europe', type: 'Regular', msb: 49, lsb: 4, pc: 1, slot: 35, source: SoundSource.expansion),
  SxVoice(name: 'PortoGitLite', category: 'Europe', type: 'Regular', msb: 49, lsb: 5, pc: 11, slot: 36, source: SoundSource.expansion),
  SxVoice(name: 'PrimTamburaPluck', category: 'Europe', type: 'Regular', msb: 49, lsb: 9, pc: 36, slot: 37, source: SoundSource.expansion),
  SxVoice(name: 'TamburaTremTutti', category: 'Europe', type: 'Regular', msb: 49, lsb: 4, pc: 18, slot: 38, source: SoundSource.expansion),
  SxVoice(name: 'TamburaVeloSw', category: 'Europe', type: 'Regular', msb: 49, lsb: 9, pc: 35, slot: 39, source: SoundSource.expansion),
  SxVoice(name: 'TromboneStac', category: 'Europe', type: 'Regular', msb: 49, lsb: 4, pc: 5, slot: 40, source: SoundSource.expansion),
  SxVoice(name: 'TubaStac', category: 'Europe', type: 'Regular', msb: 49, lsb: 4, pc: 8, slot: 41, source: SoundSource.expansion),
  SxVoice(name: 'BalkanPercussion', category: 'Europe', type: 'SFX', msb: 126, lsb: 1, pc: 12, slot: 42, source: SoundSource.expansion),
  SxVoice(name: 'GochDrums', category: 'Europe', type: 'SFX', msb: 126, lsb: 1, pc: 13, slot: 43, source: SoundSource.expansion),
  SxVoice(name: 'BalkanPowerDrums', category: 'Europe', type: 'SFX', msb: 126, lsb: 1, pc: 14, slot: 44, source: SoundSource.expansion),
  SxVoice(name: 'FlamencoKit', category: 'Europe', type: 'SFX', msb: 126, lsb: 1, pc: 16, slot: 45, source: SoundSource.expansion),
  SxVoice(name: 'DancePowerKit', category: 'Europe', type: 'SFX', msb: 126, lsb: 1, pc: 19, slot: 46, source: SoundSource.expansion),
  SxVoice(name: 'RomaniaDrumkit', category: 'Europe', type: 'SFX', msb: 126, lsb: 1, pc: 23, slot: 47, source: SoundSource.expansion),
  SxVoice(name: 'EthnicPercKit2', category: 'Europe', type: 'SFX', msb: 126, lsb: 1, pc: 27, slot: 48, source: SoundSource.expansion),
  SxVoice(name: 'Trompeta', category: 'Latin America', type: 'Regular', msb: 50, lsb: 2, pc: 49, slot: 49, source: SoundSource.expansion),
  SxVoice(name: 'TrompetaCorta', category: 'Latin America', type: 'Regular', msb: 50, lsb: 2, pc: 53, slot: 50, source: SoundSource.expansion),
  SxVoice(name: 'BajoSexto', category: 'Latin America', type: 'Regular', msb: 50, lsb: 2, pc: 55, slot: 51, source: SoundSource.expansion),
  SxVoice(name: 'AccNorteno', category: 'Latin America', type: 'Regular', msb: 50, lsb: 2, pc: 56, slot: 52, source: SoundSource.expansion),
  SxVoice(name: 'BrasilKit1', category: 'Latin America', type: 'Live!SFX', msb: 126, lsb: 0, pc: 98, slot: 53, source: SoundSource.expansion),
  SxVoice(name: 'Bateria-Tambora', category: 'Latin America', type: 'SFX', msb: 126, lsb: 1, pc: 45, slot: 54, source: SoundSource.expansion),
  SxVoice(name: 'Gritos1', category: 'Latin America', type: 'SFX', msb: 126, lsb: 1, pc: 46, slot: 55, source: SoundSource.expansion),
  SxVoice(name: 'Gritos2', category: 'Latin America', type: 'SFX', msb: 126, lsb: 1, pc: 48, slot: 56, source: SoundSource.expansion),
  SxVoice(name: 'TrompetaMega', category: 'Latin America', type: 'MegaVoice', msb: 50, lsb: 2, pc: 58, slot: 57, source: SoundSource.expansion),
  SxVoice(name: 'Trompeta S Mega', category: 'Latin America', type: 'MegaVoice', msb: 50, lsb: 2, pc: 59, slot: 58, source: SoundSource.expansion),
  SxVoice(name: 'VihuelaMega', category: 'Latin America', type: 'MegaVoice', msb: 50, lsb: 2, pc: 60, slot: 59, source: SoundSource.expansion),
  SxVoice(name: 'GuitarronMega', category: 'Latin America', type: 'MegaVoice', msb: 50, lsb: 2, pc: 61, slot: 60, source: SoundSource.expansion),
  SxVoice(name: 'AccordionMega', category: 'Latin America', type: 'MegaVoice', msb: 50, lsb: 2, pc: 62, slot: 61, source: SoundSource.expansion),
  SxVoice(name: 'NayLegato', category: 'Oriental', type: 'S.Art!', msb: 8, lsb: 34, pc: 78, slot: 62, source: SoundSource.expansion),
  SxVoice(name: 'NeyAnbanLegTrl', category: 'Oriental', type: 'S.Art!', msb: 8, lsb: 41, pc: 112, slot: 63, source: SoundSource.expansion),
  SxVoice(name: 'NeyAnbanLegato', category: 'Oriental', type: 'S.Art!', msb: 8, lsb: 42, pc: 112, slot: 64, source: SoundSource.expansion),
  SxVoice(name: 'NayOverblow', category: 'Oriental', type: 'Sweet!', msb: 104, lsb: 2, pc: 78, slot: 65, source: SoundSource.expansion),
  SxVoice(name: 'MizmarLegTril', category: 'Oriental', type: 'S.Art!', msb: 8, lsb: 37, pc: 112, slot: 66, source: SoundSource.expansion),
  SxVoice(name: 'MizmarLegato', category: 'Oriental', type: 'S.Art!', msb: 8, lsb: 38, pc: 112, slot: 67, source: SoundSource.expansion),
  SxVoice(name: 'MizmarTrill', category: 'Oriental', type: 'Regular', msb: 104, lsb: 2, pc: 112, slot: 68, source: SoundSource.expansion),
  SxVoice(name: 'Zurnalegato', category: 'Oriental', type: 'S.Art!', msb: 8, lsb: 33, pc: 112, slot: 69, source: SoundSource.expansion),
  SxVoice(name: 'ZokraLegTrill', category: 'Oriental', type: 'S.Art!', msb: 8, lsb: 35, pc: 112, slot: 70, source: SoundSource.expansion),
  SxVoice(name: 'ZokraTrill', category: 'Oriental', type: 'Regular', msb: 104, lsb: 6, pc: 112, slot: 71, source: SoundSource.expansion),
  SxVoice(name: 'KamanchehLeg', category: 'Oriental', type: 'S.Art!', msb: 8, lsb: 44, pc: 78, slot: 72, source: SoundSource.expansion),
  SxVoice(name: 'KamanchehStrong', category: 'Oriental', type: 'Live!', msb: 104, lsb: 2, pc: 111, slot: 73, source: SoundSource.expansion),
  SxVoice(name: 'OudTremolo', category: 'Oriental', type: 'Regular', msb: 104, lsb: 2, pc: 106, slot: 74, source: SoundSource.expansion),
  SxVoice(name: 'Watariat1', category: 'Oriental', type: 'Live!', msb: 104, lsb: 2, pc: 49, slot: 75, source: SoundSource.expansion),
  SxVoice(name: 'Watariat2', category: 'Oriental', type: 'Live!', msb: 104, lsb: 3, pc: 49, slot: 76, source: SoundSource.expansion),
  SxVoice(name: 'Watariat3', category: 'Oriental', type: 'Live!', msb: 104, lsb: 4, pc: 49, slot: 77, source: SoundSource.expansion),
  SxVoice(name: 'Watariat4', category: 'Oriental', type: 'Live!', msb: 104, lsb: 5, pc: 49, slot: 78, source: SoundSource.expansion),
  SxVoice(name: 'Watariat5', category: 'Oriental', type: 'Live!', msb: 104, lsb: 7, pc: 49, slot: 79, source: SoundSource.expansion),
  SxVoice(name: 'Watariat6', category: 'Oriental', type: 'Live!', msb: 104, lsb: 8, pc: 49, slot: 80, source: SoundSource.expansion),
  SxVoice(name: 'Watariat7', category: 'Oriental', type: 'Live!', msb: 104, lsb: 9, pc: 49, slot: 81, source: SoundSource.expansion),
  SxVoice(name: 'Watariat9', category: 'Oriental', type: 'Live!', msb: 104, lsb: 11, pc: 49, slot: 82, source: SoundSource.expansion),
  SxVoice(name: 'Santur', category: 'Oriental', type: 'Regular', msb: 104, lsb: 2, pc: 16, slot: 83, source: SoundSource.expansion),
  SxVoice(name: 'Qanoun1', category: 'Oriental', type: 'Regular', msb: 104, lsb: 0, pc: 108, slot: 84, source: SoundSource.expansion),
  SxVoice(name: 'QanounTremolo', category: 'Oriental', type: 'Regular', msb: 104, lsb: 1, pc: 108, slot: 85, source: SoundSource.expansion),
  SxVoice(name: 'Garmon', category: 'Oriental', type: 'Regular', msb: 104, lsb: 7, pc: 22, slot: 86, source: SoundSource.expansion),
  SxVoice(name: 'MezwedLegGrc', category: 'Oriental', type: 'S.Art!', msb: 8, lsb: 39, pc: 112, slot: 87, source: SoundSource.expansion),
  SxVoice(name: 'Solo3', category: 'Oriental', type: 'Regular', msb: 0, lsb: 109, pc: 81, slot: 88, source: SoundSource.expansion),
  SxVoice(name: 'Solo4', category: 'Oriental', type: 'Regular', msb: 0, lsb: 108, pc: 81, slot: 89, source: SoundSource.expansion),
  SxVoice(name: 'Brass2', category: 'Oriental', type: 'Regular', msb: 0, lsb: 122, pc: 63, slot: 90, source: SoundSource.expansion),
  SxVoice(name: 'A3000KhaligiKit1', category: 'Oriental', type: 'SFX', msb: 126, lsb: 0, pc: 73, slot: 91, source: SoundSource.expansion),
  SxVoice(name: 'KhaligiMixKit', category: 'Oriental', type: 'SFX', msb: 126, lsb: 0, pc: 66, slot: 92, source: SoundSource.expansion),
  SxVoice(name: 'A3000PersianKit1', category: 'Oriental', type: 'SFX', msb: 126, lsb: 0, pc: 77, slot: 93, source: SoundSource.expansion),
  SxVoice(name: 'A3000PersianKit2', category: 'Oriental', type: 'SFX', msb: 126, lsb: 0, pc: 79, slot: 94, source: SoundSource.expansion),
  SxVoice(name: 'A3000ArabicKit1', category: 'Oriental', type: 'SFX', msb: 126, lsb: 0, pc: 76, slot: 95, source: SoundSource.expansion),
  SxVoice(name: 'A3000ArabicKit2', category: 'Oriental', type: 'SFX', msb: 126, lsb: 0, pc: 78, slot: 96, source: SoundSource.expansion),
  SxVoice(name: 'KhaligiKit', category: 'Oriental', type: 'SFX', msb: 126, lsb: 0, pc: 38, slot: 97, source: SoundSource.expansion),
  SxVoice(name: 'PersianKit', category: 'Oriental', type: 'SFX', msb: 126, lsb: 0, pc: 39, slot: 98, source: SoundSource.expansion),
];

const sx700ExpansionStyles = <SxStyle>[
  SxStyle(index: 0, name: 'HighLife', category: 'African', msb: 0, lsb: 0, pc: 1, source: SoundSource.expansion),
  SxStyle(index: 1, name: 'PartyJuju', category: 'African', msb: 0, lsb: 0, pc: 2, source: SoundSource.expansion),
  SxStyle(index: 2, name: 'AfroBeat', category: 'African', msb: 0, lsb: 0, pc: 3, source: SoundSource.expansion),
  SxStyle(index: 3, name: 'HighLife2', category: 'African', msb: 0, lsb: 0, pc: 4, source: SoundSource.expansion),
  SxStyle(index: 4, name: 'OrganHighLife', category: 'African', msb: 0, lsb: 0, pc: 5, source: SoundSource.expansion),
  SxStyle(index: 5, name: 'IgboHighLife', category: 'African', msb: 0, lsb: 0, pc: 6, source: SoundSource.expansion),
  SxStyle(index: 6, name: 'Azonto', category: 'African', msb: 0, lsb: 0, pc: 7, source: SoundSource.expansion),
  SxStyle(index: 7, name: 'ModernAfrobeat', category: 'African', msb: 0, lsb: 0, pc: 8, source: SoundSource.expansion),
  SxStyle(index: 8, name: 'Makossa', category: 'African', msb: 0, lsb: 0, pc: 9, source: SoundSource.expansion),
  SxStyle(index: 9, name: 'AfricanGospel', category: 'African', msb: 0, lsb: 0, pc: 10, source: SoundSource.expansion),
  SxStyle(index: 10, name: 'Hora', category: 'Europe', msb: 0, lsb: 0, pc: 11, source: SoundSource.expansion),
  SxStyle(index: 11, name: 'Sarba', category: 'Europe', msb: 0, lsb: 0, pc: 12, source: SoundSource.expansion),
  SxStyle(index: 12, name: 'Dyskoteka PL', category: 'Europe', msb: 0, lsb: 0, pc: 13, source: SoundSource.expansion),
  SxStyle(index: 13, name: 'Fisa Bajon', category: 'Europe', msb: 0, lsb: 0, pc: 14, source: SoundSource.expansion),
  SxStyle(index: 14, name: 'Pizzica', category: 'Europe', msb: 0, lsb: 0, pc: 15, source: SoundSource.expansion),
  SxStyle(index: 15, name: 'Saltarello', category: 'Europe', msb: 0, lsb: 0, pc: 16, source: SoundSource.expansion),
  SxStyle(index: 16, name: 'Zouk', category: 'Europe', msb: 0, lsb: 0, pc: 17, source: SoundSource.expansion),
  SxStyle(index: 17, name: 'BalalaikaWalz', category: 'Europe', msb: 0, lsb: 0, pc: 18, source: SoundSource.expansion),
  SxStyle(index: 18, name: 'TroikaFolk RU', category: 'Europe', msb: 0, lsb: 0, pc: 19, source: SoundSource.expansion),
  SxStyle(index: 19, name: 'Cerge HR', category: 'Europe', msb: 0, lsb: 0, pc: 20, source: SoundSource.expansion),
  SxStyle(index: 20, name: 'Flam Buleria', category: 'Europe', msb: 0, lsb: 0, pc: 21, source: SoundSource.expansion),
  SxStyle(index: 21, name: 'CsardasModern', category: 'Europe', msb: 0, lsb: 0, pc: 22, source: SoundSource.expansion),
  SxStyle(index: 22, name: 'Mata HR', category: 'Europe', msb: 0, lsb: 0, pc: 23, source: SoundSource.expansion),
  SxStyle(index: 23, name: 'Balkan Dance', category: 'Europe', msb: 0, lsb: 0, pc: 24, source: SoundSource.expansion),
  SxStyle(index: 24, name: 'GypsyJazz', category: 'Europe', msb: 0, lsb: 0, pc: 25, source: SoundSource.expansion),
  SxStyle(index: 25, name: 'MontiCzardas', category: 'Europe', msb: 0, lsb: 0, pc: 26, source: SoundSource.expansion),
  SxStyle(index: 26, name: 'Scand Shuffle', category: 'Europe', msb: 0, lsb: 0, pc: 27, source: SoundSource.expansion),
  SxStyle(index: 27, name: 'WaltzPolka', category: 'Europe', msb: 0, lsb: 0, pc: 28, source: SoundSource.expansion),
  SxStyle(index: 28, name: 'Bk Brass Pop', category: 'Europe', msb: 0, lsb: 0, pc: 29, source: SoundSource.expansion),
  SxStyle(index: 29, name: 'CaptainSax6-8', category: 'Europe', msb: 0, lsb: 0, pc: 30, source: SoundSource.expansion),
  SxStyle(index: 30, name: 'TranceSylvan', category: 'Europe', msb: 0, lsb: 0, pc: 31, source: SoundSource.expansion),
  SxStyle(index: 31, name: 'Syrtorumba', category: 'Europe', msb: 0, lsb: 0, pc: 32, source: SoundSource.expansion),
  SxStyle(index: 32, name: 'Tsamikos', category: 'Europe', msb: 0, lsb: 0, pc: 33, source: SoundSource.expansion),
  SxStyle(index: 33, name: 'Isa', category: 'Europe', msb: 0, lsb: 0, pc: 34, source: SoundSource.expansion),
  SxStyle(index: 34, name: 'Fado', category: 'Europe', msb: 0, lsb: 0, pc: 35, source: SoundSource.expansion),
  SxStyle(index: 35, name: 'PuertoRicoFolk', category: 'Europe', msb: 0, lsb: 0, pc: 36, source: SoundSource.expansion),
  SxStyle(index: 36, name: 'MariachiJoropo', category: 'Latin America', msb: 0, lsb: 0, pc: 37, source: SoundSource.expansion),
  SxStyle(index: 37, name: 'MariachiPolca', category: 'Latin America', msb: 0, lsb: 0, pc: 38, source: SoundSource.expansion),
  SxStyle(index: 38, name: 'MariValsFast', category: 'Latin America', msb: 0, lsb: 0, pc: 39, source: SoundSource.expansion),
  SxStyle(index: 39, name: 'MariachiValsSlow', category: 'Latin America', msb: 0, lsb: 0, pc: 40, source: SoundSource.expansion),
  SxStyle(index: 40, name: 'MariachiSlow2-4', category: 'Latin America', msb: 0, lsb: 0, pc: 41, source: SoundSource.expansion),
  SxStyle(index: 41, name: 'MariZapateado', category: 'Latin America', msb: 0, lsb: 0, pc: 42, source: SoundSource.expansion),
  SxStyle(index: 42, name: 'CumbiaDelNorte', category: 'Latin America', msb: 0, lsb: 0, pc: 43, source: SoundSource.expansion),
  SxStyle(index: 43, name: 'DelNorte2-4', category: 'Latin America', msb: 0, lsb: 0, pc: 44, source: SoundSource.expansion),
  SxStyle(index: 44, name: 'ValsDelNorte', category: 'Latin America', msb: 0, lsb: 0, pc: 45, source: SoundSource.expansion),
  SxStyle(index: 45, name: 'CumbiaBrusca', category: 'Latin America', msb: 0, lsb: 0, pc: 46, source: SoundSource.expansion),
  SxStyle(index: 46, name: 'CumbiaSonidera', category: 'Latin America', msb: 0, lsb: 0, pc: 47, source: SoundSource.expansion),
  SxStyle(index: 47, name: 'CumbiaSonora', category: 'Latin America', msb: 0, lsb: 0, pc: 48, source: SoundSource.expansion),
  SxStyle(index: 48, name: 'CumbiaTNT', category: 'Latin America', msb: 0, lsb: 0, pc: 49, source: SoundSource.expansion),
  SxStyle(index: 49, name: 'Punta', category: 'Latin America', msb: 0, lsb: 0, pc: 50, source: SoundSource.expansion),
  SxStyle(index: 50, name: 'TambitoPop', category: 'Latin America', msb: 0, lsb: 0, pc: 51, source: SoundSource.expansion),
  SxStyle(index: 51, name: 'ValsPeruano', category: 'Latin America', msb: 0, lsb: 0, pc: 52, source: SoundSource.expansion),
  SxStyle(index: 52, name: 'ChaabiModern', category: 'Oriental', msb: 0, lsb: 0, pc: 53, source: SoundSource.expansion),
  SxStyle(index: 53, name: 'SaidiDance', category: 'Oriental', msb: 0, lsb: 0, pc: 54, source: SoundSource.expansion),
  SxStyle(index: 54, name: 'Dosari', category: 'Oriental', msb: 0, lsb: 0, pc: 55, source: SoundSource.expansion),
  SxStyle(index: 55, name: 'Khebaiti4-4', category: 'Oriental', msb: 0, lsb: 0, pc: 56, source: SoundSource.expansion),
  SxStyle(index: 56, name: '6-8Pop', category: 'Oriental', msb: 0, lsb: 0, pc: 57, source: SoundSource.expansion),
];
