// PSR-SX700 style catalog. MIDI uses bank LSB = index ~/ 128, PC = index % 128 + 1,
// plus Yamaha panel SysEx with the 0-based style index.
import 'style.dart';

const sx700Styles = <SxStyle>[
  SxStyle(index: 0, name: '8Beat Modern', category: 'Pop', msb: 0, lsb: 0, pc: 1),
  SxStyle(index: 1, name: '8Beat Pop', category: 'Pop', msb: 0, lsb: 0, pc: 2),
  SxStyle(index: 2, name: 'Pop Funk', category: 'Pop', msb: 0, lsb: 0, pc: 3),
  SxStyle(index: 3, name: 'Pop Shuffle', category: 'Pop', msb: 0, lsb: 0, pc: 4),
  SxStyle(index: 4, name: 'Pop Rock', category: 'Pop', msb: 0, lsb: 0, pc: 5),
  SxStyle(index: 5, name: 'Guitar Pop', category: 'Pop', msb: 0, lsb: 0, pc: 6),
  SxStyle(index: 6, name: 'Indie Pop', category: 'Pop', msb: 0, lsb: 0, pc: 7),
  SxStyle(index: 7, name: 'Electro Pop', category: 'Pop', msb: 0, lsb: 0, pc: 8),
  SxStyle(index: 8, name: 'Synth Pop', category: 'Pop', msb: 0, lsb: 0, pc: 9),
  SxStyle(index: 9, name: '80s Pop', category: 'Pop', msb: 0, lsb: 0, pc: 10),
  SxStyle(index: 10, name: '90s Pop', category: 'Pop', msb: 0, lsb: 0, pc: 11),
  SxStyle(index: 11, name: 'Brit Pop', category: 'Pop', msb: 0, lsb: 0, pc: 12),
  SxStyle(index: 12, name: 'City Pop', category: 'Pop', msb: 0, lsb: 0, pc: 13),
  SxStyle(index: 13, name: 'Soft Pop', category: 'Pop', msb: 0, lsb: 0, pc: 14),
  SxStyle(index: 14, name: 'Power Pop', category: 'Pop', msb: 0, lsb: 0, pc: 15),
  SxStyle(index: 15, name: 'Pop Ballad', category: 'Pop', msb: 0, lsb: 0, pc: 16),
  SxStyle(index: 16, name: 'Acoustic Pop', category: 'Pop', msb: 0, lsb: 0, pc: 17),
  SxStyle(index: 17, name: 'Festival Pop', category: 'Pop', msb: 0, lsb: 0, pc: 18),
  SxStyle(index: 18, name: 'Radio Pop', category: 'Pop', msb: 0, lsb: 0, pc: 19),
  SxStyle(index: 19, name: 'Pop Groove', category: 'Pop', msb: 0, lsb: 0, pc: 20),
  SxStyle(index: 20, name: 'Pop 16Beat', category: 'Pop', msb: 0, lsb: 0, pc: 21),
  SxStyle(index: 21, name: 'Pop Chart', category: 'Pop', msb: 0, lsb: 0, pc: 22),
  SxStyle(index: 22, name: 'Pop Anthem', category: 'Pop', msb: 0, lsb: 0, pc: 23),
  SxStyle(index: 23, name: 'Pop Dance', category: 'Pop', msb: 0, lsb: 0, pc: 24),
  SxStyle(index: 24, name: 'Pop Soul', category: 'Pop', msb: 0, lsb: 0, pc: 25),
  SxStyle(index: 25, name: 'Showtime', category: 'Entertainer', msb: 0, lsb: 0, pc: 26),
  SxStyle(index: 26, name: 'Big Entertainer', category: 'Entertainer', msb: 0, lsb: 0, pc: 27),
  SxStyle(index: 27, name: 'TV Theme', category: 'Entertainer', msb: 0, lsb: 0, pc: 28),
  SxStyle(index: 28, name: 'Variety Show', category: 'Entertainer', msb: 0, lsb: 0, pc: 29),
  SxStyle(index: 29, name: 'Cabaret', category: 'Entertainer', msb: 0, lsb: 0, pc: 30),
  SxStyle(index: 30, name: 'Music Hall', category: 'Entertainer', msb: 0, lsb: 0, pc: 31),
  SxStyle(index: 31, name: 'Broadway Pop', category: 'Entertainer', msb: 0, lsb: 0, pc: 32),
  SxStyle(index: 32, name: 'Circus March', category: 'Entertainer', msb: 0, lsb: 0, pc: 33),
  SxStyle(index: 33, name: 'Vaudeville', category: 'Entertainer', msb: 0, lsb: 0, pc: 34),
  SxStyle(index: 34, name: 'Game Show', category: 'Entertainer', msb: 0, lsb: 0, pc: 35),
  SxStyle(index: 35, name: 'Opener', category: 'Entertainer', msb: 0, lsb: 0, pc: 36),
  SxStyle(index: 36, name: 'Fanfare Pop', category: 'Entertainer', msb: 0, lsb: 0, pc: 37),
  SxStyle(index: 37, name: 'Orchestra Hit', category: 'Entertainer', msb: 0, lsb: 0, pc: 38),
  SxStyle(index: 38, name: 'Medley Pop', category: 'Entertainer', msb: 0, lsb: 0, pc: 39),
  SxStyle(index: 39, name: 'Party Band', category: 'Entertainer', msb: 0, lsb: 0, pc: 40),
  SxStyle(index: 40, name: 'Unplugged Show', category: 'Entertainer', msb: 0, lsb: 0, pc: 41),
  SxStyle(index: 41, name: 'Club Entertainer', category: 'Entertainer', msb: 0, lsb: 0, pc: 42),
  SxStyle(index: 42, name: 'Piano Bar', category: 'Entertainer', msb: 0, lsb: 0, pc: 43),
  SxStyle(index: 43, name: 'Lounge Show', category: 'Entertainer', msb: 0, lsb: 0, pc: 44),
  SxStyle(index: 44, name: 'Hit Parade', category: 'Entertainer', msb: 0, lsb: 0, pc: 45),
  SxStyle(index: 45, name: 'Blockbuster', category: 'Movie & Show', msb: 0, lsb: 0, pc: 46),
  SxStyle(index: 46, name: 'Adventure Film', category: 'Movie & Show', msb: 0, lsb: 0, pc: 47),
  SxStyle(index: 47, name: 'Epic Orchestra', category: 'Movie & Show', msb: 0, lsb: 0, pc: 48),
  SxStyle(index: 48, name: 'Suspense', category: 'Movie & Show', msb: 0, lsb: 0, pc: 49),
  SxStyle(index: 49, name: 'Western Movie', category: 'Movie & Show', msb: 0, lsb: 0, pc: 50),
  SxStyle(index: 50, name: 'Sci-Fi', category: 'Movie & Show', msb: 0, lsb: 0, pc: 51),
  SxStyle(index: 51, name: 'Romance Movie', category: 'Movie & Show', msb: 0, lsb: 0, pc: 52),
  SxStyle(index: 52, name: 'Action Cue', category: 'Movie & Show', msb: 0, lsb: 0, pc: 53),
  SxStyle(index: 53, name: 'Cartoon Score', category: 'Movie & Show', msb: 0, lsb: 0, pc: 54),
  SxStyle(index: 54, name: 'Fantasy Theme', category: 'Movie & Show', msb: 0, lsb: 0, pc: 55),
  SxStyle(index: 55, name: 'Detective', category: 'Movie & Show', msb: 0, lsb: 0, pc: 56),
  SxStyle(index: 56, name: 'War Epic', category: 'Movie & Show', msb: 0, lsb: 0, pc: 57),
  SxStyle(index: 57, name: 'Space Odyssey', category: 'Movie & Show', msb: 0, lsb: 0, pc: 58),
  SxStyle(index: 58, name: 'Superhero', category: 'Movie & Show', msb: 0, lsb: 0, pc: 59),
  SxStyle(index: 59, name: 'Silent Movie', category: 'Movie & Show', msb: 0, lsb: 0, pc: 60),
  SxStyle(index: 60, name: 'Musical Theatre', category: 'Movie & Show', msb: 0, lsb: 0, pc: 61),
  SxStyle(index: 61, name: 'Opera Pop', category: 'Movie & Show', msb: 0, lsb: 0, pc: 62),
  SxStyle(index: 62, name: 'Soundtrack Ballad', category: 'Movie & Show', msb: 0, lsb: 0, pc: 63),
  SxStyle(index: 63, name: 'Trailer', category: 'Movie & Show', msb: 0, lsb: 0, pc: 64),
  SxStyle(index: 64, name: 'Classic Film', category: 'Movie & Show', msb: 0, lsb: 0, pc: 65),
  SxStyle(index: 65, name: 'Modern R&B', category: 'R&B', msb: 0, lsb: 0, pc: 66),
  SxStyle(index: 66, name: 'Soul Beat', category: 'R&B', msb: 0, lsb: 0, pc: 67),
  SxStyle(index: 67, name: 'Neo Soul', category: 'R&B', msb: 0, lsb: 0, pc: 68),
  SxStyle(index: 68, name: 'Funk Pop', category: 'R&B', msb: 0, lsb: 0, pc: 69),
  SxStyle(index: 69, name: 'Disco Funk', category: 'R&B', msb: 0, lsb: 0, pc: 70),
  SxStyle(index: 70, name: 'Motown', category: 'R&B', msb: 0, lsb: 0, pc: 71),
  SxStyle(index: 71, name: 'Gospel Soul', category: 'R&B', msb: 0, lsb: 0, pc: 72),
  SxStyle(index: 72, name: 'Quiet Storm', category: 'R&B', msb: 0, lsb: 0, pc: 73),
  SxStyle(index: 73, name: 'Hip Hop Soul', category: 'R&B', msb: 0, lsb: 0, pc: 74),
  SxStyle(index: 74, name: '90s R&B', category: 'R&B', msb: 0, lsb: 0, pc: 75),
  SxStyle(index: 75, name: 'New Jack', category: 'R&B', msb: 0, lsb: 0, pc: 76),
  SxStyle(index: 76, name: 'Philly Soul', category: 'R&B', msb: 0, lsb: 0, pc: 77),
  SxStyle(index: 77, name: 'Slow Jam', category: 'R&B', msb: 0, lsb: 0, pc: 78),
  SxStyle(index: 78, name: 'Funk Shuffle', category: 'R&B', msb: 0, lsb: 0, pc: 79),
  SxStyle(index: 79, name: 'Go Go', category: 'R&B', msb: 0, lsb: 0, pc: 80),
  SxStyle(index: 80, name: 'Urban Groove', category: 'R&B', msb: 0, lsb: 0, pc: 81),
  SxStyle(index: 81, name: 'R&B Ballad', category: 'R&B', msb: 0, lsb: 0, pc: 82),
  SxStyle(index: 82, name: 'Club Soul', category: 'R&B', msb: 0, lsb: 0, pc: 83),
  SxStyle(index: 83, name: 'Classic Funk', category: 'R&B', msb: 0, lsb: 0, pc: 84),
  SxStyle(index: 84, name: 'Blues Soul', category: 'R&B', msb: 0, lsb: 0, pc: 85),
  SxStyle(index: 85, name: 'Piano Ballad', category: 'Ballad', msb: 0, lsb: 0, pc: 86),
  SxStyle(index: 86, name: 'Pop Ballad 12/8', category: 'Ballad', msb: 0, lsb: 0, pc: 87),
  SxStyle(index: 87, name: 'Love Song', category: 'Ballad', msb: 0, lsb: 0, pc: 88),
  SxStyle(index: 88, name: 'Soft Rock Ballad', category: 'Ballad', msb: 0, lsb: 0, pc: 89),
  SxStyle(index: 89, name: 'Soul Ballad', category: 'Ballad', msb: 0, lsb: 0, pc: 90),
  SxStyle(index: 90, name: 'Country Ballad', category: 'Ballad', msb: 0, lsb: 0, pc: 91),
  SxStyle(index: 91, name: 'Orchestral Ballad', category: 'Ballad', msb: 0, lsb: 0, pc: 92),
  SxStyle(index: 92, name: '6/8 Ballad', category: 'Ballad', msb: 0, lsb: 0, pc: 93),
  SxStyle(index: 93, name: 'Acoustic Ballad', category: 'Ballad', msb: 0, lsb: 0, pc: 94),
  SxStyle(index: 94, name: 'Power Ballad', category: 'Ballad', msb: 0, lsb: 0, pc: 95),
  SxStyle(index: 95, name: 'Celtic Ballad', category: 'Ballad', msb: 0, lsb: 0, pc: 96),
  SxStyle(index: 96, name: 'Movie Ballad', category: 'Ballad', msb: 0, lsb: 0, pc: 97),
  SxStyle(index: 97, name: 'Gospel Ballad', category: 'Ballad', msb: 0, lsb: 0, pc: 98),
  SxStyle(index: 98, name: 'Easy Ballad', category: 'Ballad', msb: 0, lsb: 0, pc: 99),
  SxStyle(index: 99, name: 'Night Ballad', category: 'Ballad', msb: 0, lsb: 0, pc: 100),
  SxStyle(index: 100, name: 'Modern Ballad', category: 'Ballad', msb: 0, lsb: 0, pc: 101),
  SxStyle(index: 101, name: 'Slow Rock', category: 'Ballad', msb: 0, lsb: 0, pc: 102),
  SxStyle(index: 102, name: 'Unplugged Ballad', category: 'Ballad', msb: 0, lsb: 0, pc: 103),
  SxStyle(index: 103, name: 'Strings Ballad', category: 'Ballad', msb: 0, lsb: 0, pc: 104),
  SxStyle(index: 104, name: '8Beat Ballad', category: 'Ballad', msb: 0, lsb: 0, pc: 105),
  SxStyle(index: 105, name: 'Dance Pop', category: 'Dance', msb: 0, lsb: 0, pc: 106),
  SxStyle(index: 106, name: 'House', category: 'Dance', msb: 0, lsb: 0, pc: 107),
  SxStyle(index: 107, name: 'Deep House', category: 'Dance', msb: 0, lsb: 0, pc: 108),
  SxStyle(index: 108, name: 'EDM Anthem', category: 'Dance', msb: 0, lsb: 0, pc: 109),
  SxStyle(index: 109, name: 'Trance', category: 'Dance', msb: 0, lsb: 0, pc: 110),
  SxStyle(index: 110, name: 'Techno', category: 'Dance', msb: 0, lsb: 0, pc: 111),
  SxStyle(index: 111, name: 'Euro Dance', category: 'Dance', msb: 0, lsb: 0, pc: 112),
  SxStyle(index: 112, name: 'Disco Night', category: 'Dance', msb: 0, lsb: 0, pc: 113),
  SxStyle(index: 113, name: 'Garage', category: 'Dance', msb: 0, lsb: 0, pc: 114),
  SxStyle(index: 114, name: 'Drum & Bass', category: 'Dance', msb: 0, lsb: 0, pc: 115),
  SxStyle(index: 115, name: 'Dubstep', category: 'Dance', msb: 0, lsb: 0, pc: 116),
  SxStyle(index: 116, name: 'Electro House', category: 'Dance', msb: 0, lsb: 0, pc: 117),
  SxStyle(index: 117, name: 'Club Dance', category: 'Dance', msb: 0, lsb: 0, pc: 118),
  SxStyle(index: 118, name: '90s Dance', category: 'Dance', msb: 0, lsb: 0, pc: 119),
  SxStyle(index: 119, name: 'Italo Disco', category: 'Dance', msb: 0, lsb: 0, pc: 120),
  SxStyle(index: 120, name: 'Synthwave', category: 'Dance', msb: 0, lsb: 0, pc: 121),
  SxStyle(index: 121, name: 'Big Room', category: 'Dance', msb: 0, lsb: 0, pc: 122),
  SxStyle(index: 122, name: 'Progressive', category: 'Dance', msb: 0, lsb: 0, pc: 123),
  SxStyle(index: 123, name: 'Tropical House', category: 'Dance', msb: 0, lsb: 0, pc: 124),
  SxStyle(index: 124, name: 'Afro House', category: 'Dance', msb: 0, lsb: 0, pc: 125),
  SxStyle(index: 125, name: 'Celtic Folk', category: 'World', msb: 0, lsb: 0, pc: 126),
  SxStyle(index: 126, name: 'Irish Jig', category: 'World', msb: 0, lsb: 0, pc: 127),
  SxStyle(index: 127, name: 'Scottish', category: 'World', msb: 0, lsb: 0, pc: 128),
  SxStyle(index: 128, name: 'Polka Folk', category: 'World', msb: 0, lsb: 1, pc: 1),
  SxStyle(index: 129, name: 'Gypsy Swing', category: 'World', msb: 0, lsb: 1, pc: 2),
  SxStyle(index: 130, name: 'Balkan', category: 'World', msb: 0, lsb: 1, pc: 3),
  SxStyle(index: 131, name: 'Klezmer', category: 'World', msb: 0, lsb: 1, pc: 4),
  SxStyle(index: 132, name: 'Greek', category: 'World', msb: 0, lsb: 1, pc: 5),
  SxStyle(index: 133, name: 'Turkish Pop', category: 'World', msb: 0, lsb: 1, pc: 6),
  SxStyle(index: 134, name: 'Arabic Pop', category: 'World', msb: 0, lsb: 1, pc: 7),
  SxStyle(index: 135, name: 'Bollywood', category: 'World', msb: 0, lsb: 1, pc: 8),
  SxStyle(index: 136, name: 'Bhangra', category: 'World', msb: 0, lsb: 1, pc: 9),
  SxStyle(index: 137, name: 'Chinese Pop', category: 'World', msb: 0, lsb: 1, pc: 10),
  SxStyle(index: 138, name: 'Japanese Pop', category: 'World', msb: 0, lsb: 1, pc: 11),
  SxStyle(index: 139, name: 'Korean Pop', category: 'World', msb: 0, lsb: 1, pc: 12),
  SxStyle(index: 140, name: 'African Pop', category: 'World', msb: 0, lsb: 1, pc: 13),
  SxStyle(index: 141, name: 'Highlife', category: 'World', msb: 0, lsb: 1, pc: 14),
  SxStyle(index: 142, name: 'Reggae', category: 'World', msb: 0, lsb: 1, pc: 15),
  SxStyle(index: 143, name: 'Ska', category: 'World', msb: 0, lsb: 1, pc: 16),
  SxStyle(index: 144, name: 'Calypso', category: 'World', msb: 0, lsb: 1, pc: 17),
  SxStyle(index: 145, name: 'Soca', category: 'World', msb: 0, lsb: 1, pc: 18),
  SxStyle(index: 146, name: 'Hawaiian', category: 'World', msb: 0, lsb: 1, pc: 19),
  SxStyle(index: 147, name: 'Polynesian', category: 'World', msb: 0, lsb: 1, pc: 20),
  SxStyle(index: 148, name: 'Andean', category: 'World', msb: 0, lsb: 1, pc: 21),
  SxStyle(index: 149, name: 'Flamenco Pop', category: 'World', msb: 0, lsb: 1, pc: 22),
  SxStyle(index: 150, name: 'Pianist 8Beat', category: 'Pianist', msb: 0, lsb: 1, pc: 23),
  SxStyle(index: 151, name: 'Pianist Ballad', category: 'Pianist', msb: 0, lsb: 1, pc: 24),
  SxStyle(index: 152, name: 'Pianist Jazz', category: 'Pianist', msb: 0, lsb: 1, pc: 25),
  SxStyle(index: 153, name: 'Pianist Bossa', category: 'Pianist', msb: 0, lsb: 1, pc: 26),
  SxStyle(index: 154, name: 'Pianist Gospel', category: 'Pianist', msb: 0, lsb: 1, pc: 27),
  SxStyle(index: 155, name: 'Pianist Pop', category: 'Pianist', msb: 0, lsb: 1, pc: 28),
  SxStyle(index: 156, name: 'Pianist Shuffle', category: 'Pianist', msb: 0, lsb: 1, pc: 29),
  SxStyle(index: 157, name: 'Pianist Waltz', category: 'Pianist', msb: 0, lsb: 1, pc: 30),
  SxStyle(index: 158, name: 'Pianist 16Beat', category: 'Pianist', msb: 0, lsb: 1, pc: 31),
  SxStyle(index: 159, name: 'Pianist Country', category: 'Pianist', msb: 0, lsb: 1, pc: 32),
  SxStyle(index: 160, name: 'Pianist Blues', category: 'Pianist', msb: 0, lsb: 1, pc: 33),
  SxStyle(index: 161, name: 'Pianist Latin', category: 'Pianist', msb: 0, lsb: 1, pc: 34),
  SxStyle(index: 162, name: 'Pianist Rock', category: 'Pianist', msb: 0, lsb: 1, pc: 35),
  SxStyle(index: 163, name: 'Pianist Soul', category: 'Pianist', msb: 0, lsb: 1, pc: 36),
  SxStyle(index: 164, name: 'Pianist Free', category: 'Pianist', msb: 0, lsb: 1, pc: 37),
  SxStyle(index: 165, name: 'Pianist Classic', category: 'Pianist', msb: 0, lsb: 1, pc: 38),
  SxStyle(index: 166, name: 'Pianist New Age', category: 'Pianist', msb: 0, lsb: 1, pc: 39),
  SxStyle(index: 167, name: 'Pianist Boogie', category: 'Pianist', msb: 0, lsb: 1, pc: 40),
  SxStyle(index: 168, name: 'Pianist Swing', category: 'Pianist', msb: 0, lsb: 1, pc: 41),
  SxStyle(index: 169, name: 'Pianist Folk', category: 'Pianist', msb: 0, lsb: 1, pc: 42),
  SxStyle(index: 170, name: 'Big Band', category: 'Jazz', msb: 0, lsb: 1, pc: 43),
  SxStyle(index: 171, name: 'Swingfox', category: 'Jazz', msb: 0, lsb: 1, pc: 44),
  SxStyle(index: 172, name: 'Jazz Club', category: 'Jazz', msb: 0, lsb: 1, pc: 45),
  SxStyle(index: 173, name: 'Bebop', category: 'Jazz', msb: 0, lsb: 1, pc: 46),
  SxStyle(index: 174, name: 'Cool Jazz', category: 'Jazz', msb: 0, lsb: 1, pc: 47),
  SxStyle(index: 175, name: 'Jazz Waltz', category: 'Jazz', msb: 0, lsb: 1, pc: 48),
  SxStyle(index: 176, name: 'Jazz Ballad', category: 'Jazz', msb: 0, lsb: 1, pc: 49),
  SxStyle(index: 177, name: 'Jazz Rock', category: 'Jazz', msb: 0, lsb: 1, pc: 50),
  SxStyle(index: 178, name: 'Fusion', category: 'Jazz', msb: 0, lsb: 1, pc: 51),
  SxStyle(index: 179, name: 'Smooth Jazz', category: 'Jazz', msb: 0, lsb: 1, pc: 52),
  SxStyle(index: 180, name: 'Dixieland', category: 'Jazz', msb: 0, lsb: 1, pc: 53),
  SxStyle(index: 181, name: 'Gypsy Jazz', category: 'Jazz', msb: 0, lsb: 1, pc: 54),
  SxStyle(index: 182, name: 'Organ Jazz', category: 'Jazz', msb: 0, lsb: 1, pc: 55),
  SxStyle(index: 183, name: 'Jazz Funk', category: 'Jazz', msb: 0, lsb: 1, pc: 56),
  SxStyle(index: 184, name: 'Modal Jazz', category: 'Jazz', msb: 0, lsb: 1, pc: 57),
  SxStyle(index: 185, name: 'Latin Jazz', category: 'Jazz', msb: 0, lsb: 1, pc: 58),
  SxStyle(index: 186, name: 'Jazz Samba', category: 'Jazz', msb: 0, lsb: 1, pc: 59),
  SxStyle(index: 187, name: 'Jazz Shuffle', category: 'Jazz', msb: 0, lsb: 1, pc: 60),
  SxStyle(index: 188, name: 'Piano Trio', category: 'Jazz', msb: 0, lsb: 1, pc: 61),
  SxStyle(index: 189, name: 'Jazz Blues', category: 'Jazz', msb: 0, lsb: 1, pc: 62),
  SxStyle(index: 190, name: 'Country Pop', category: 'Country', msb: 0, lsb: 1, pc: 63),
  SxStyle(index: 191, name: 'Country Swing', category: 'Country', msb: 0, lsb: 1, pc: 64),
  SxStyle(index: 192, name: 'Country Rock', category: 'Country', msb: 0, lsb: 1, pc: 65),
  SxStyle(index: 193, name: 'Bluegrass', category: 'Country', msb: 0, lsb: 1, pc: 66),
  SxStyle(index: 194, name: 'Honky Tonk', category: 'Country', msb: 0, lsb: 1, pc: 67),
  SxStyle(index: 195, name: 'Country Ballad 2', category: 'Country', msb: 0, lsb: 1, pc: 68),
  SxStyle(index: 196, name: 'Nashville', category: 'Country', msb: 0, lsb: 1, pc: 69),
  SxStyle(index: 197, name: 'Country Shuffle', category: 'Country', msb: 0, lsb: 1, pc: 70),
  SxStyle(index: 198, name: 'Western Swing', category: 'Country', msb: 0, lsb: 1, pc: 71),
  SxStyle(index: 199, name: 'Country Two Step', category: 'Country', msb: 0, lsb: 1, pc: 72),
  SxStyle(index: 200, name: 'Country Waltz', category: 'Country', msb: 0, lsb: 1, pc: 73),
  SxStyle(index: 201, name: 'Americana', category: 'Country', msb: 0, lsb: 1, pc: 74),
  SxStyle(index: 202, name: 'Country Folk', category: 'Country', msb: 0, lsb: 1, pc: 75),
  SxStyle(index: 203, name: 'Country Train', category: 'Country', msb: 0, lsb: 1, pc: 76),
  SxStyle(index: 204, name: 'Country 8Beat', category: 'Country', msb: 0, lsb: 1, pc: 77),
  SxStyle(index: 205, name: 'Modern Country', category: 'Country', msb: 0, lsb: 1, pc: 78),
  SxStyle(index: 206, name: 'Country Gospel', category: 'Country', msb: 0, lsb: 1, pc: 79),
  SxStyle(index: 207, name: 'Outlaw', category: 'Country', msb: 0, lsb: 1, pc: 80),
  SxStyle(index: 208, name: 'Country Blues', category: 'Country', msb: 0, lsb: 1, pc: 81),
  SxStyle(index: 209, name: 'Country Disco', category: 'Country', msb: 0, lsb: 1, pc: 82),
  SxStyle(index: 210, name: 'Bossa Nova', category: 'Latin', msb: 0, lsb: 1, pc: 83),
  SxStyle(index: 211, name: 'Samba', category: 'Latin', msb: 0, lsb: 1, pc: 84),
  SxStyle(index: 212, name: 'Salsa', category: 'Latin', msb: 0, lsb: 1, pc: 85),
  SxStyle(index: 213, name: 'Mambo', category: 'Latin', msb: 0, lsb: 1, pc: 86),
  SxStyle(index: 214, name: 'Cha Cha', category: 'Latin', msb: 0, lsb: 1, pc: 87),
  SxStyle(index: 215, name: 'Rumba', category: 'Latin', msb: 0, lsb: 1, pc: 88),
  SxStyle(index: 216, name: 'Merengue', category: 'Latin', msb: 0, lsb: 1, pc: 89),
  SxStyle(index: 217, name: 'Bachata', category: 'Latin', msb: 0, lsb: 1, pc: 90),
  SxStyle(index: 218, name: 'Cumbia', category: 'Latin', msb: 0, lsb: 1, pc: 91),
  SxStyle(index: 219, name: 'Reggaeton', category: 'Latin', msb: 0, lsb: 1, pc: 92),
  SxStyle(index: 220, name: 'Tango', category: 'Latin', msb: 0, lsb: 1, pc: 93),
  SxStyle(index: 221, name: 'Paso Doble', category: 'Latin', msb: 0, lsb: 1, pc: 94),
  SxStyle(index: 222, name: 'Beguine', category: 'Latin', msb: 0, lsb: 1, pc: 95),
  SxStyle(index: 223, name: 'Bolero', category: 'Latin', msb: 0, lsb: 1, pc: 96),
  SxStyle(index: 224, name: 'Songo', category: 'Latin', msb: 0, lsb: 1, pc: 97),
  SxStyle(index: 225, name: 'Latin Pop', category: 'Latin', msb: 0, lsb: 1, pc: 98),
  SxStyle(index: 226, name: 'Latin Rock', category: 'Latin', msb: 0, lsb: 1, pc: 99),
  SxStyle(index: 227, name: 'Afro Cuban', category: 'Latin', msb: 0, lsb: 1, pc: 100),
  SxStyle(index: 228, name: 'Guaguanco', category: 'Latin', msb: 0, lsb: 1, pc: 101),
  SxStyle(index: 229, name: 'Pachanga', category: 'Latin', msb: 0, lsb: 1, pc: 102),
  SxStyle(index: 230, name: 'Slow Waltz', category: 'Ballroom', msb: 0, lsb: 1, pc: 103),
  SxStyle(index: 231, name: 'Viennese Waltz', category: 'Ballroom', msb: 0, lsb: 1, pc: 104),
  SxStyle(index: 232, name: 'Foxtrot', category: 'Ballroom', msb: 0, lsb: 1, pc: 105),
  SxStyle(index: 233, name: 'Quickstep', category: 'Ballroom', msb: 0, lsb: 1, pc: 106),
  SxStyle(index: 234, name: 'Tango Ballroom', category: 'Ballroom', msb: 0, lsb: 1, pc: 107),
  SxStyle(index: 235, name: 'Slow Foxtrot', category: 'Ballroom', msb: 0, lsb: 1, pc: 108),
  SxStyle(index: 236, name: 'Jive', category: 'Ballroom', msb: 0, lsb: 1, pc: 109),
  SxStyle(index: 237, name: 'Cha Cha Ballroom', category: 'Ballroom', msb: 0, lsb: 1, pc: 110),
  SxStyle(index: 238, name: 'Rumba Ballroom', category: 'Ballroom', msb: 0, lsb: 1, pc: 111),
  SxStyle(index: 239, name: 'Samba Ballroom', category: 'Ballroom', msb: 0, lsb: 1, pc: 112),
  SxStyle(index: 240, name: 'Paso Ballroom', category: 'Ballroom', msb: 0, lsb: 1, pc: 113),
  SxStyle(index: 241, name: 'Swing Ballroom', category: 'Ballroom', msb: 0, lsb: 1, pc: 114),
  SxStyle(index: 242, name: 'Polka Ballroom', category: 'Ballroom', msb: 0, lsb: 1, pc: 115),
  SxStyle(index: 243, name: 'Mazurka', category: 'Ballroom', msb: 0, lsb: 1, pc: 116),
  SxStyle(index: 244, name: 'Minuet', category: 'Ballroom', msb: 0, lsb: 1, pc: 117),
  SxStyle(index: 245, name: 'English Waltz', category: 'Ballroom', msb: 0, lsb: 1, pc: 118),
  SxStyle(index: 246, name: 'Boston Waltz', category: 'Ballroom', msb: 0, lsb: 1, pc: 119),
  SxStyle(index: 247, name: 'Baroque Dance', category: 'Ballroom', msb: 0, lsb: 1, pc: 120),
  SxStyle(index: 248, name: 'Classic Waltz', category: 'Ballroom', msb: 0, lsb: 1, pc: 121),
  SxStyle(index: 249, name: 'Ballroom Mix', category: 'Ballroom', msb: 0, lsb: 1, pc: 122),
  SxStyle(index: 250, name: 'Classic Rock', category: 'Rock', msb: 0, lsb: 1, pc: 123),
  SxStyle(index: 251, name: 'Hard Rock', category: 'Rock', msb: 0, lsb: 1, pc: 124),
  SxStyle(index: 252, name: 'Soft Rock', category: 'Rock', msb: 0, lsb: 1, pc: 125),
  SxStyle(index: 253, name: 'Blues Rock', category: 'Rock', msb: 0, lsb: 1, pc: 126),
  SxStyle(index: 254, name: 'Folk Rock', category: 'Rock', msb: 0, lsb: 1, pc: 127),
  SxStyle(index: 255, name: 'Punk Rock', category: 'Rock', msb: 0, lsb: 1, pc: 128),
  SxStyle(index: 256, name: 'Arena Rock', category: 'Rock', msb: 0, lsb: 2, pc: 1),
  SxStyle(index: 257, name: 'Southern Rock', category: 'Rock', msb: 0, lsb: 2, pc: 2),
  SxStyle(index: 258, name: 'Prog Rock', category: 'Rock', msb: 0, lsb: 2, pc: 3),
  SxStyle(index: 259, name: 'Indie Rock', category: 'Rock', msb: 0, lsb: 2, pc: 4),
  SxStyle(index: 260, name: 'Rock Shuffle', category: 'Rock', msb: 0, lsb: 2, pc: 5),
  SxStyle(index: 261, name: 'Rock Ballad', category: 'Rock', msb: 0, lsb: 2, pc: 6),
  SxStyle(index: 262, name: 'Surf Rock', category: 'Rock', msb: 0, lsb: 2, pc: 7),
  SxStyle(index: 263, name: 'Glam Rock', category: 'Rock', msb: 0, lsb: 2, pc: 8),
  SxStyle(index: 264, name: 'Metal Rock', category: 'Rock', msb: 0, lsb: 2, pc: 9),
  SxStyle(index: 265, name: 'Rock 8Beat', category: 'Rock', msb: 0, lsb: 2, pc: 10),
  SxStyle(index: 266, name: 'Rock 16Beat', category: 'Rock', msb: 0, lsb: 2, pc: 11),
  SxStyle(index: 267, name: 'Boogie Rock', category: 'Rock', msb: 0, lsb: 2, pc: 12),
  SxStyle(index: 268, name: 'Rockabilly', category: 'Rock', msb: 0, lsb: 2, pc: 13),
  SxStyle(index: 269, name: 'Grunge', category: 'Rock', msb: 0, lsb: 2, pc: 14),
  SxStyle(index: 270, name: 'March', category: 'Traditional', msb: 0, lsb: 2, pc: 15),
  SxStyle(index: 271, name: 'Polka', category: 'Traditional', msb: 0, lsb: 2, pc: 16),
  SxStyle(index: 272, name: 'Oberkrainer', category: 'Traditional', msb: 0, lsb: 2, pc: 17),
  SxStyle(index: 273, name: 'French Musette', category: 'Traditional', msb: 0, lsb: 2, pc: 18),
  SxStyle(index: 274, name: 'German Waltz', category: 'Traditional', msb: 0, lsb: 2, pc: 19),
  SxStyle(index: 275, name: 'Alpine', category: 'Traditional', msb: 0, lsb: 2, pc: 20),
  SxStyle(index: 276, name: 'Brass Band', category: 'Traditional', msb: 0, lsb: 2, pc: 21),
  SxStyle(index: 277, name: 'Folk Dance', category: 'Traditional', msb: 0, lsb: 2, pc: 22),
  SxStyle(index: 278, name: 'Hymn', category: 'Traditional', msb: 0, lsb: 2, pc: 23),
  SxStyle(index: 279, name: 'Christmas 8Beat', category: 'Traditional', msb: 0, lsb: 2, pc: 24),
  SxStyle(index: 280, name: 'Christmas Waltz', category: 'Traditional', msb: 0, lsb: 2, pc: 25),
  SxStyle(index: 281, name: 'Christmas Ballad', category: 'Traditional', msb: 0, lsb: 2, pc: 26),
  SxStyle(index: 282, name: 'Church', category: 'Traditional', msb: 0, lsb: 2, pc: 27),
  SxStyle(index: 283, name: 'Fanfare', category: 'Traditional', msb: 0, lsb: 2, pc: 28),
  SxStyle(index: 284, name: 'Traditional Jazz', category: 'Traditional', msb: 0, lsb: 2, pc: 29),
  SxStyle(index: 285, name: 'Barbershop', category: 'Traditional', msb: 0, lsb: 2, pc: 30),
  SxStyle(index: 286, name: 'Celtic March', category: 'Traditional', msb: 0, lsb: 2, pc: 31),
  SxStyle(index: 287, name: 'Pipe Band', category: 'Traditional', msb: 0, lsb: 2, pc: 32),
  SxStyle(index: 288, name: 'Sea Shanty', category: 'Traditional', msb: 0, lsb: 2, pc: 33),
  SxStyle(index: 289, name: 'Festival March', category: 'Traditional', msb: 0, lsb: 2, pc: 34),
  SxStyle(index: 290, name: 'Easy Listening', category: 'Ballad & Easy', msb: 0, lsb: 2, pc: 35),
  SxStyle(index: 291, name: 'Adult Contemporary', category: 'Ballad & Easy', msb: 0, lsb: 2, pc: 36),
  SxStyle(index: 292, name: 'Smooth Pop', category: 'Ballad & Easy', msb: 0, lsb: 2, pc: 37),
  SxStyle(index: 293, name: 'Night Club', category: 'Ballad & Easy', msb: 0, lsb: 2, pc: 38),
  SxStyle(index: 294, name: 'Cocktail', category: 'Ballad & Easy', msb: 0, lsb: 2, pc: 39),
  SxStyle(index: 295, name: 'New Age Pad', category: 'Ballad & Easy', msb: 0, lsb: 2, pc: 40),
  SxStyle(index: 296, name: 'Ambient Pop', category: 'Ballad & Easy', msb: 0, lsb: 2, pc: 41),
  SxStyle(index: 297, name: 'Chillout', category: 'Ballad & Easy', msb: 0, lsb: 2, pc: 42),
  SxStyle(index: 298, name: 'Lounge', category: 'Ballad & Easy', msb: 0, lsb: 2, pc: 43),
  SxStyle(index: 299, name: 'Downtempo', category: 'Ballad & Easy', msb: 0, lsb: 2, pc: 44),
  SxStyle(index: 300, name: 'Soft Funk', category: 'Ballad & Easy', msb: 0, lsb: 2, pc: 45),
  SxStyle(index: 301, name: 'Easy Shuffle', category: 'Ballad & Easy', msb: 0, lsb: 2, pc: 46),
  SxStyle(index: 302, name: 'Easy 8Beat', category: 'Ballad & Easy', msb: 0, lsb: 2, pc: 47),
  SxStyle(index: 303, name: 'Easy Latin', category: 'Ballad & Easy', msb: 0, lsb: 2, pc: 48),
  SxStyle(index: 304, name: 'Easy Jazz', category: 'Ballad & Easy', msb: 0, lsb: 2, pc: 49),
  SxStyle(index: 305, name: 'Movie Easy', category: 'Ballad & Easy', msb: 0, lsb: 2, pc: 50),
  SxStyle(index: 306, name: 'Soft Disco', category: 'Ballad & Easy', msb: 0, lsb: 2, pc: 51),
  SxStyle(index: 307, name: 'Soft House', category: 'Ballad & Easy', msb: 0, lsb: 2, pc: 52),
  SxStyle(index: 308, name: 'Soft Reggae', category: 'Ballad & Easy', msb: 0, lsb: 2, pc: 53),
  SxStyle(index: 309, name: 'Soft Country', category: 'Ballad & Easy', msb: 0, lsb: 2, pc: 54),
];
